python sft_paddleocr_vl.py \
    --model_path ../PaddleOCR-VL/PaddleOCR-VL-0.9B \
    --images_dir ./data/images \
    --caption_file ./data/labels.txt \
    --task ocr \
    --output_dir ./sft_output \
    --num_train_epochs 50 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --learning_rate 1e-4 \
    --warmup_steps 100 \
    --logging_steps 10 \
    --save_steps 100 \
    --eval_strategy no \
    --bf16 \
    --gradient_accumulation_steps 2
